// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMLDDkx4r2RpixZ2uWahkxhpd_5v5a9zs',
    appId: '1:108497124848:web:ab81345df3c0155678f135',
    messagingSenderId: '108497124848',
    projectId: 'learn-app-4b56a',
    authDomain: 'learn-app-4b56a.firebaseapp.com',
    storageBucket: 'learn-app-4b56a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_phiyl_mxNhhAsZGoD74tM6EjuTqDxg',
    appId: '1:108497124848:android:fa798a764631831278f135',
    messagingSenderId: '108497124848',
    projectId: 'learn-app-4b56a',
    storageBucket: 'learn-app-4b56a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJT49H0jhpzBjnmXADK9fLnHIffP5sj8',
    appId: '1:108497124848:ios:bf5dd894ff38958978f135',
    messagingSenderId: '108497124848',
    projectId: 'learn-app-4b56a',
    storageBucket: 'learn-app-4b56a.appspot.com',
    iosBundleId: 'com.example.learnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaJT49H0jhpzBjnmXADK9fLnHIffP5sj8',
    appId: '1:108497124848:ios:bf5dd894ff38958978f135',
    messagingSenderId: '108497124848',
    projectId: 'learn-app-4b56a',
    storageBucket: 'learn-app-4b56a.appspot.com',
    iosBundleId: 'com.example.learnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMLDDkx4r2RpixZ2uWahkxhpd_5v5a9zs',
    appId: '1:108497124848:web:ddbb4f4ba3c8779478f135',
    messagingSenderId: '108497124848',
    projectId: 'learn-app-4b56a',
    authDomain: 'learn-app-4b56a.firebaseapp.com',
    storageBucket: 'learn-app-4b56a.appspot.com',
  );
}
